""" Store global constants """
# LEDmatrix configuration
CHAIN_LENGTH = 3
PARALLEL_CHAINS = 2

# The dimensions of the board
BOARD_WIDTH = 96
BOARD_HEIGHT = 64

# Game properties
NUM_GAMES = 6
GAME_SPEED = 300
DROP_SPACING = 16

# Heuristic factors
COMPLETE_LINES_FACTOR = 0.75
TETRIS_PREFERENCE_FACTOR = 100
COVERED_EMPTY_SPACES_FACTOR = -0.5
AVERAGE_COLUMN_HEIGHT_FACTOR = -0.5
COLUMN_HEIGHT_VARIANCE_FACTOR = -0.1
